#################################################################################
# Hydra configuration for predicting the function of proteins. 
# Values can be modified via CLI overrides, e.g.:
#   python -m src.predict.run_predict model=path/to/model.pt
#################################################################################

model: 
  path: outputs/classify_unpooled/phageGAP_95_retrained_30e/cnn_model1_final.pt

seed: 42

device: cuda

all:
  bool: False

unknowns:
  bool: False # set to False if input is a new fasta 
  embedding: 
  ids: 

new_fasta:
  path: protein_sequences/NCBI/BASEL_proteins_1_file/protein_fastas_concatenated.faa

embeddings:
  model_type: prot_t5
  only_last: true

pool: 
  layers: [] # optional explicit layers list, e.g. [1, 3, 5, 9]; take last hidden layer/final representation if empty
  strategy: mean # mean | max | FC

hydra:
  run:
    dir: outputs/predict/${now:%Y-%m-%d_%H-%M-%S}