#################################################################################
# Hydra configuration for classifying protein sequence embeddings. 
# Values can be modified via CLI overrides, e.g.:
#   python -m src.classify.run_classify optimize=True
#################################################################################

seed: 42

cluster:
  representatives: inputs/only_phage_repr_assigned_cat_0.95.tsv  
  cat: inputs/Keywords_map.csv

data:
  embedding: outputs/embed/ProtT5/protein_embeddings_last_True_prot_t5.h5 
  pooled: False
  embed_dim: 1024 # 1024 (pro(s)t) | 960 (esmc_300m) | 1152 (esmc_600m) | 1536 (esm3) | 1280 (glm2, esm2_650, pst-TL-T) | 800 (pst-TL-P) |  2560 (esm2_3b) | 640 (esm2_150m)
  test_size: 0.15
  val_size: 0.15
  num_workers: 12
  colname: assigned_subcat
  colname_top: assigned_top
  map_colname: Subcategory
  map_colname_top: Top_Category

bac_vir:
  bool: True
  embedded: outputs/embed/bac_vir/ProtT5/protein_embeddings_last_True_prot_t5.h5 

features:
  bool: False
  path: 
  top_n: 

context:
  bool: False
  size: 

optimize:
  bool: False
  cnn_mlp: False # if True, optimizes CNN + MLP. Else optimizes CNN + FC
  cnn_flattened: False
  mean_max: False
  epochs: 5
  n_trials: 200
  batch_size_train: 128
  batch_size_test: 1000
  cnn_use_linear_attention: False
  cnn_use_non_linear_attention: False

train:
  device: cuda
  log_interval: 10

models:
  model1:
    mlp:
      num_dimensions: 
      num_neurons: 
      dropout: 
    context:
      num_heads: 
      dim_feedforward: 
      num_layers: 
      dropout: 
    cnn:
      bool: True
      num_conv_layers: 2
      num_filters: [384, 384] 
      kernel_sizes: [11, 9] 
      dropout: 0.17
      dilations: [7, 6] 
      use_dilation: True
      mean_max: False
      use_linear_attention: False
      use_nonlinear_attention: False
    cnn_flattened:
      bool: False
      num_conv_layers: 
      num_filters: 
      kernel_sizes: 
      dropout: 
      dilations: 
      use_dilation: 
      mean_max: 
    cnn_mlp:
      bool: False
      num_conv_layers: 
      num_filters: 
      kernel_sizes: 
      dropout_conv:
      dilations:
      use_dilation: 
      use_linear_attention: 
      use_nonlinear_attention: 
      num_dimensions: 
      num_neurons: 
      dropout_mlp: 


optim:
  optimizer: AdamW # Adam | AdamW | SGD
  lr: 0.00154509923679428
  weight_decay: 0.0001
  epochs: 30
  batch_size: 128

hydra:
  run:
    dir: ${get_output_dir:${optimize.bool},${context.bool},${data.pooled}}